use crate::battery::Credits;
use anyhow::{Context, Result};
use serde::Deserialize;
use std::collections::BTreeMap;
use std::fmt::Write;
use std::path::{Path, PathBuf};

#[derive(Deserialize)]
struct Summary {
    cases_passed: u32,
    cases_tested: u32,
    vectors_passed: u32,
    vectors_failed: u32,
}

/// Read for LOC / unsafe / build status only: the pass/fail verdict comes from
/// the battery `summary.json`, not from here.
#[derive(Deserialize)]
struct CaseResult {
    /// `Some("build failed")` iff the crate did not compile; any other value,
    /// or absent, means it compiled.
    error: Option<String>,
    loc: Option<Loc>,
    #[serde(rename = "unsafe")]
    unsafe_: Option<Unsafe>,
}

#[derive(Deserialize)]
struct Loc {
    code: u32,
}

#[derive(Deserialize)]
struct Unsafe {
    lines: u32,
}

struct BatteryRow {
    agent: String,
    battery: String,
    cases_passed: u32,
    cases_tested: u32,
    cases_built: u32,
    vectors_passed: u32,
    vectors_total: u32,
    c_loc: u32,
    total_loc: u32,
    unsafe_lines: u32,
}

/// Where a tool's artifacts live, DERIVED from what the run attested rather than written down.
///
/// This replaces three frozen literals -- `kiro/unrecorded`, `claude/claude-opus-5-1m`,
/// `codex/gpt-5.4` -- a second definition of "which agents exist and where" from before
/// `<tool>/<model>`. The existence invariant below asserted THOSE names, so a legitimate rename made
/// table generation refuse outright. That is why `tables/` was empty.
fn attested_dir(attested: &Attested, tool: &str) -> Option<String> {
    attested
        .entries()
        .find(|(run, _)| run.label() == tool)
        .map(|(run, _)| format!("results/Test-Corpus/{}", run.dir))
}

/// How one run is spelled in the two places that disagree: `label` is what a table's Agent column
/// prints, `dir` is where its artifacts live. One `String` was both until the store grew a model level.
#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Debug)]
pub struct Run {
    label: String,
    dir: String,
}

impl Run {
    /// Derived from the resolved paths, so a caller cannot pair one run's label with another's
    /// directory. `label` is what a table's Agent column prints; `dir` is where the artifacts are.
    fn of(paths: &crate::battery::Paths) -> Self {
        let tool = crate::cli::tool_dir(paths.tool);
        let label = match paths.variant {
            crate::cli::Variant::Default => tool.to_string(),
            v => format!("{tool}-{}", v.dir()),
        };
        Self {
            label,
            dir: paths
                .results_dir
                .strip_prefix(
                    paths
                        .results_dir
                        .ancestors()
                        .nth(3)
                        .unwrap_or(&paths.results_dir),
                )
                .unwrap_or(&paths.results_dir)
                .to_string_lossy()
                .into_owned(),
        }
    }

    pub fn label(&self) -> &str {
        &self.label
    }
}

/// The (run, unit) pairs a run RESOLVED, and so the only ones a table may report: `report` used
/// to walk `results/` and publish whatever it found, which by `eval::Source`'s measurement
/// was ~95% unattested. A set built BY the run cannot name a pair the run did not resolve.
#[derive(Debug, Default)]
pub struct Attested(std::collections::BTreeSet<(Run, String)>);

impl Attested {
    pub fn insert(&mut self, paths: &crate::battery::Paths, unit: &str) {
        self.0.insert((Run::of(paths), unit.to_owned()));
    }

    /// Every (run, unit) this run may publish. A reporter iterating THIS cannot silently omit one.
    pub fn entries(&self) -> impl Iterator<Item = (&Run, &str)> {
        self.0.iter().map(|(r, u)| (r, u.as_str()))
    }

    /// Take another run's attestation into this one. Every tool's rows belong in one `tables/` write:
    /// writing per tool has each rewrite the file from its own rows and blank the rest.
    pub fn absorb(&mut self, other: Self) {
        self.0.extend(other.0);
    }

    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }
}

/// One row per upstream C library. Separate from [`generate`] because the datasets are earned by separate
/// runs and a run writes only what it resolved -- folded in, a Test-Corpus run would blank these rows.
pub fn generate_harvest_bench(repo_root: &Path, attested: &Attested) -> Result<()> {
    anyhow::ensure!(
        !attested.is_empty(),
        "refusing to write the harvest-bench table: this run resolved no project"
    );
    let results_dir = repo_root.join("results/HarvestBench");
    let tables_dir = repo_root.join("tables");
    std::fs::create_dir_all(&tables_dir)?;

    let mut out = String::new();
    out.push_str(
        "% GENERATED by `harvest-tools run HB` from results/HarvestBench/. Do not edit by hand.\n",
    );
    out.push_str(
        "% Tool & Project & Builds & Tests & Rust LOC & unsafe. Tests = upstream GoogleTest cases\n         % passing; a build that failed has no tests.\n",
    );
    // Driven by what this run ATTESTED, not `read_dir`: walking the filesystem made absence invisible
    // twice -- a missing record dropped its row, and an attested project with no dir was never visited.
    // Either way the table published N-1 rows of N and announced success.
    for (run, project) in attested.entries() {
        let record =
            scored_phase_dir(&results_dir.join(&run.dir).join(project)).join("result.json");
        let r: HarvestBenchRow = read_json(&record).with_context(|| {
            format!(
                "{}/{project} is in this run's scope but has no readable record at {}",
                run.label,
                record.display()
            )
        })?;
        let graded = r.tests_ok + r.tests_failed;
        let code = r.loc.as_ref().map_or(0, |l| l.code);
        let unsafe_pct = if code > 0 {
            let (u, c) = (r.unsafe_.as_ref().map_or(0, |u| u.lines), code);
            format!("{:.0}\\%", u as f64 / c as f64 * 100.0)
        } else {
            "--".to_string()
        };
        out.push_str(&format!(
            "{} & {project} & {} & {}/{graded} & {} & {unsafe_pct} \\\\\n\\hline\n",
            display_label(run.label()),
            if r.build_ok { "yes" } else { "\\textbf{no}" },
            r.tests_ok,
            r.loc
                .as_ref()
                .map_or("--".to_string(), |l| fmt_commas(l.code as u32)),
        ));
    }

    let path = tables_dir.join("harvest-bench.tex");
    std::fs::write(&path, &out)?;
    println!("\u{2705} Wrote {}", path.display());
    Ok(())
}

/// Only what the table reports. Absent metrics print `--`, never a zero nobody measured.
#[derive(Deserialize)]
struct HarvestBenchRow {
    #[serde(default)]
    tests_ok: usize,
    #[serde(default)]
    tests_failed: usize,
    #[serde(default)]
    build_ok: bool,
    #[serde(rename = "unsafe")]
    unsafe_: Option<crate::analyse::metrics::UnsafeCounts>,
    loc: Option<crate::analyse::metrics::LocCounts>,
}

pub fn generate(repo_root: &Path, attested: &Attested) -> Result<()> {
    anyhow::ensure!(
        !attested.is_empty(),
        "refusing to write tables/: this run resolved nothing, so every row would come from \
         artifacts it did not produce"
    );
    let results_dir = repo_root.join("results/Test-Corpus");
    let test_corpus_dir = repo_root.join("test-corpus/Public-Tests");
    let tables_dir = repo_root.join("tables");
    std::fs::create_dir_all(&tables_dir)?;

    // results.md's "C LOC" column comes from the test-corpus submodule; without
    // it every C LOC would silently become 0 and clobber the committed file, so
    // results.md is skipped. tractor.tex uses Rust LOC and never needs the corpus.
    let has_c_corpus = test_corpus_dir.is_dir();

    // C LOC is a property of the battery, identical for every agent.
    let mut c_loc_cache: BTreeMap<String, u32> = BTreeMap::new();

    let mut rows: Vec<BatteryRow> = Vec::new();

    // Attested-driven like `generate_harvest_bench`: the tree is `<harness>/<model>/<battery>` keyed
    // and `<baseline>/<battery>` for the docker arms, so no fixed-depth walk reads both.
    for (run, battery) in attested.entries() {
        {
            let agent = run.label();
            let battery = battery.to_string();
            let bat_dir = results_dir.join(&run.dir).join(&battery);
            if !bat_dir.is_dir() {
                println!(
                    "   \u{23ed}\u{fe0f}  {agent}/{battery}: no directory at {}",
                    bat_dir.display()
                );
                continue;
            }

            let summary_path = bat_dir.join("summary.json");
            let summary: Summary = match read_json(&summary_path) {
                Some(s) => s,
                None => continue,
            };

            let totals = aggregate_cases(&bat_dir, &test_corpus_dir.join(&battery));

            let c_loc = *c_loc_cache
                .entry(battery.clone())
                .or_insert_with(|| count_c_loc_battery(&test_corpus_dir, &battery));

            rows.push(BatteryRow {
                agent: agent.to_string(),
                battery: battery.clone(),
                cases_passed: summary.cases_passed,
                cases_tested: summary.cases_tested,
                cases_built: totals.cases_built,
                vectors_passed: summary.vectors_passed,
                vectors_total: summary.vectors_passed + summary.vectors_failed,
                c_loc,
                total_loc: totals.total_loc,
                unsafe_lines: totals.unsafe_lines,
            });

            // Kiro's PRE-verify numbers, emitted as a synthetic "kiro-translate"
            // agent row so \ActorKiroNoValidate* and TRACTOR_TABLE_ROWS can key
            // on it without a separate results tree.
            if agent == "kiro" {
                if let Some(nv) = read_json::<Summary>(&bat_dir.join("summary_translated.json")) {
                    let nv_totals = aggregate_cases_phase(
                        &bat_dir,
                        &test_corpus_dir.join(&battery),
                        Some(crate::battery::TRANSLATED),
                    );
                    rows.push(BatteryRow {
                        agent: "kiro-translate".to_string(),
                        battery: battery.clone(),
                        cases_passed: nv.cases_passed,
                        cases_tested: nv.cases_tested,
                        cases_built: nv_totals.cases_built,
                        vectors_passed: nv.vectors_passed,
                        vectors_total: nv.vectors_passed + nv.vectors_failed,
                        c_loc,
                        total_loc: nv_totals.total_loc,
                        unsafe_lines: nv_totals.unsafe_lines,
                    });
                }
            }
        }
    }

    let mut by_battery: BTreeMap<String, Vec<&BatteryRow>> = BTreeMap::new();
    for row in &rows {
        by_battery.entry(row.battery.clone()).or_default().push(row);
    }

    let mut all = String::new();
    writeln!(all, "# Translation Results\n")?;
    writeln!(
        all,
        "Auto-generated from validated `result.json` and `summary.json` files.\n"
    )?;

    for (battery, brows) in &by_battery {
        writeln!(all, "## {battery}\n")?;
        writeln!(all, "| Agent | Cases Passed | Vectors Passed | C LOC | Rust LOC | Unsafe Lines | Unsafe % |")?;
        writeln!(
            all,
            "|-------|-------------|----------------|-------|----------|-------------|----------|"
        )?;
        for r in brows {
            let unsafe_pct = if r.total_loc > 0 {
                format!("{:.1}%", r.unsafe_lines as f64 / r.total_loc as f64 * 100.0)
            } else {
                "N/A".into()
            };
            writeln!(
                all,
                "| {} | {}/{} | {}/{} | {} | {} | {} | {} |",
                r.agent,
                r.cases_passed,
                r.cases_tested,
                r.vectors_passed,
                r.vectors_total,
                r.c_loc,
                r.total_loc,
                r.unsafe_lines,
                unsafe_pct,
            )?;
        }
        writeln!(all)?;
    }

    writeln!(all, "## Summary: Cases Passed\n")?;
    let agents: Vec<String> = rows
        .iter()
        .map(|r| r.agent.clone())
        .collect::<std::collections::BTreeSet<_>>()
        .into_iter()
        .collect();
    write!(all, "| Battery |")?;
    for a in &agents {
        write!(all, " {} |", a)?;
    }
    writeln!(all)?;
    write!(all, "|---------|")?;
    for _ in &agents {
        write!(all, "------|")?;
    }
    writeln!(all)?;
    for (battery, brows) in &by_battery {
        let lookup: BTreeMap<&str, &BatteryRow> =
            brows.iter().map(|r| (r.agent.as_str(), *r)).collect();
        write!(all, "| {} |", battery)?;
        for a in &agents {
            if let Some(r) = lookup.get(a.as_str()) {
                write!(all, " {}/{} |", r.cases_passed, r.cases_tested)?;
            } else {
                write!(all, " — |")?;
            }
        }
        writeln!(all)?;
    }
    writeln!(all)?;

    // See has_c_corpus: rewriting without the corpus would zero the C LOC column.
    let out_path = tables_dir.join("results.md");
    if has_c_corpus {
        std::fs::write(&out_path, &all)?;
        println!("✅ Wrote {}", out_path.display());
    } else {
        println!(
            "⚠️  Skipped {} (test-corpus submodule not checked out; \
             C LOC would be zeroed). Run `git submodule update --init test-corpus` \
             to regenerate it.",
            out_path.display(),
        );
    }

    let tex = generate_tractor_tex(&rows);
    let tex_path = tables_dir.join("tractor.tex");
    std::fs::write(&tex_path, &tex)?;
    println!("✅ Wrote {}", tex_path.display());

    let kiro_dir = attested_dir(attested, "kiro");
    let numbers = generate_numbers_tex(&rows, repo_root, kiro_dir.as_deref());
    let numbers_path = tables_dir.join("numbers.tex");
    std::fs::write(&numbers_path, &numbers)?;
    println!("✅ Wrote {}", numbers_path.display());

    let datasets = generate_datasets_tex(repo_root);
    let datasets_path = tables_dir.join("datasets.tex");
    std::fs::write(&datasets_path, &datasets)?;
    println!("✅ Wrote {}", datasets_path.display());

    let promptsens = generate_prompt_sensitivity_tex(repo_root, &rows);
    let promptsens_path = tables_dir.join("prompt-sensitivity.tex");
    std::fs::write(&promptsens_path, &promptsens)?;
    println!("✅ Wrote {}", promptsens_path.display());

    let manual = generate_manual_tex(repo_root);
    let manual_path = tables_dir.join("manual.tex");
    std::fs::write(&manual_path, &manual)?;
    println!("✅ Wrote {}", manual_path.display());

    // ── Invariant checks. Deliberately over the DATA the tables were built
    //    from, not over compile-time constants: a renamed/missing input dir or a
    //    lost symlink must fail generation, not silently change a number. ──

    // (1) Every case of every battery IN SCOPE. A constant 338 could not tell a partial tree from a
    //     deliberately narrower published set; scoped, it still fires on a battery losing cases.
    let mut per_agent_total: BTreeMap<&str, u32> = BTreeMap::new();
    for r in &rows {
        *per_agent_total.entry(r.agent.as_str()).or_insert(0) += r.cases_tested;
    }
    let tractor_total = per_agent_total.values().copied().max().unwrap_or(0);
    let in_scope: std::collections::BTreeSet<&str> =
        rows.iter().map(|r| r.battery.as_str()).collect();
    let expected: u32 = EXPECTED_BATTERY_SIZES
        .iter()
        .filter(|(bat, _)| in_scope.contains(bat))
        .map(|(_, n)| n)
        .sum();
    anyhow::ensure!(
        tractor_total == expected,
        "TRACTOR invariant failed: max agent case total is {tractor_total}, expected {expected}"
    );

    // (1b) Also pin each battery, so compensating errors cannot inflate one
    //      denominator while the total still sums to 338.
    const EXPECTED_BATTERY_SIZES: &[(&str, u32)] = &[
        ("B01_synthetic", 85),
        ("B01_organic", 38),
        ("B02_synthetic", 42),
        ("B02_organic", 44),
        ("P00_perlin_noise", 1),
        ("P01_sphincs_plus", 128),
    ];
    let mut battery_max: BTreeMap<&str, u32> = BTreeMap::new();
    for r in &rows {
        let e = battery_max.entry(r.battery.as_str()).or_insert(0);
        *e = (*e).max(r.cases_tested);
    }
    for (bat, expected) in EXPECTED_BATTERY_SIZES {
        if let Some(&got) = battery_max.get(bat) {
            anyhow::ensure!(
                got == *expected,
                "TRACTOR battery-size invariant failed: {bat} max cases_tested is {got}, expected {expected}"
            );
        }
    }
    let battery_sum: u32 = EXPECTED_BATTERY_SIZES.iter().map(|(_, n)| n).sum();
    anyhow::ensure!(
        battery_sum == 338,
        "TRACTOR battery sizes sum to {battery_sum}, expected 338"
    );

    // (1c) A renamed/missing agent dir emits a plausible all-zeros row ("0/338") that trips no other
    //      invariant and is indistinguishable from a genuine baseline zero. The dirs come from the
    //      ATTESTATION, so the check still fires on a rename between attesting and reading, and it no
    //      longer names a layout that has since moved on. Naming three literal paths is what made this
    //      refuse every table after the `<tool>/<model>` migration.
    for (run, _) in attested.entries() {
        let dir = results_dir.join(&run.dir);
        anyhow::ensure!(
            dir.is_dir(),
            "TRACTOR agent-dir invariant failed: {} was attested but is missing \
             (a rename would silently emit a 0/338 row).",
            dir.display()
        );
    }
    // Without at least one summary_translated.json the pre-verify scoring pass
    // did not run, and the no-validate row would silently read 0/338.
    // Only when kiro is among the attested tools: a run of claude alone has no pre-verify pass to
    // check, and demanding one would refuse a table that is honestly narrower.
    if let Some(kiro) = attested_dir(attested, "kiro") {
        let kiro = repo_root.join(&kiro);
        anyhow::ensure!(
            sorted_read_dir(&kiro)
                .map(|bats| bats
                    .iter()
                    .any(|b| b.path().join("summary_translated.json").is_file()))
                .unwrap_or(false),
            "no-validate invariant failed: no {}/<battery>/summary_translated.json found (the \
             pre-verify scoring pass did not run; \\ActorKiroNoValidate* would be 0/338).",
            kiro.display()
        );
    }
    // (2) P01/P00 must collapse to one distinct source. If symlinks did not
    //     survive checkout (core.symlinks=false materializes them as real dirs),
    //     every config counts and LOC inflates ~120x silently. Skipped when the corpus
    //     is absent: dedup cannot run and datasets.tex omits these rows anyway.
    if has_c_corpus {
        for (bat, expected_cases) in [("P01_sphincs_plus", 1u32), ("P00_perlin_noise", 1u32)] {
            let bat_dir = test_corpus_dir.join(bat);
            if !bat_dir.is_dir() {
                continue;
            }
            let mut distinct: std::collections::HashSet<std::path::PathBuf> =
                std::collections::HashSet::new();
            let mut case_dirs = 0u32;
            if let Ok(cases) = sorted_read_dir(&bat_dir) {
                for ce in cases {
                    let tc = ce.path().join("test_case");
                    if !tc.is_dir() {
                        continue;
                    }
                    case_dirs += 1;
                    distinct.insert(std::fs::canonicalize(&tc).unwrap_or(tc));
                }
            }
            anyhow::ensure!(
                distinct.len() as u32 == expected_cases,
                "shared-source dedup invariant failed: {bat} has {case_dirs} case dirs collapsing to \
                 {} distinct sources, expected {expected_cases} — symlinks likely did not survive checkout \
                 (core.symlinks=false?), which would inflate LOC. Re-clone with symlink support.",
                distinct.len()
            );
        }
    }

    // (3) Catch a renamed/removed macro here rather than as a LaTeX "Undefined
    //     control sequence".
    let macros_used = repo_root.join("macros_used.txt");
    if macros_used.is_file() {
        let emitted = format!("{numbers}\n{manual}");
        let mut missing = Vec::new();
        for line in std::fs::read_to_string(&macros_used)?.lines() {
            let name = line.trim();
            if name.is_empty() || name.starts_with('#') {
                continue;
            }
            if !emitted.contains(&format!("{{\\{name}}}")) {
                missing.push(name.to_string());
            }
        }
        anyhow::ensure!(
            missing.is_empty(),
            "macros_used.txt lists macros the generator does not emit: {missing:?}"
        );
    }

    Ok(())
}

/// Comma thousands separators, matching the paper's dataset table.
fn fmt_commas(n: u32) -> String {
    let s = n.to_string();
    let bytes = s.as_bytes();
    let mut out = String::new();
    let len = bytes.len();
    for (i, b) in bytes.iter().enumerate() {
        if i > 0 && (len - i).is_multiple_of(3) {
            out.push(',');
        }
        out.push(*b as char);
    }
    out
}

/// Rounds half away from zero (`f64::round`); 0 for an empty slice.
fn median_round(values: &[u32]) -> u32 {
    if values.is_empty() {
        return 0;
    }
    let mut v = values.to_vec();
    v.sort_unstable();
    let n = v.len();
    let m = if n % 2 == 1 {
        v[n / 2] as f64
    } else {
        (v[n / 2 - 1] as f64 + v[n / 2] as f64) / 2.0
    };
    m.round() as u32
}

/// TRACTOR battery directory names, in paper order (results-dir keys).
const TRACTOR_BATTERY_DIRS: &[&str] = &[
    "B01_synthetic",
    "B01_organic",
    "B02_synthetic",
    "B02_organic",
    "P00_perlin_noise",
    "P01_sphincs_plus",
];

/// Cases whose corpus `test_case/` symlinks to one real source are counted once
/// (P01's 128 configs → one source). The single definition used by BOTH
/// tab:datasets and the TRACTOR total/mean prose macros, so they cannot disagree.
fn tractor_battery_c_locs(corpus: &Path, dir_name: &str) -> Vec<u32> {
    let bat_dir = corpus.join(dir_name);
    let mut locs: Vec<u32> = Vec::new();
    let mut seen: std::collections::HashSet<std::path::PathBuf> = std::collections::HashSet::new();
    if let Ok(cases) = sorted_read_dir(&bat_dir) {
        for ce in cases {
            if !ce.path().is_dir() {
                continue;
            }
            let test_case = ce.path().join("test_case");
            if !test_case.is_dir() {
                continue;
            }
            let real = std::fs::canonicalize(&test_case).unwrap_or_else(|_| test_case.clone());
            if !seen.insert(real) {
                continue;
            }
            locs.push(count_c_loc_dir(&test_case));
        }
    }
    locs
}

/// tab:datasets body: `Dataset & Cases & Total & Mean & Median & Max` per
/// battery, counting non-comment, non-blank C LOC.
fn generate_datasets_tex(repo_root: &Path) -> String {
    let mut out = String::new();
    out.push_str("% GENERATED by harvest-tools report — do not edit\n");

    let corpus = repo_root.join("test-corpus/Public-Tests");
    // (results dir name, display name), in paper order.
    let batteries: &[(&str, &str)] = &[
        ("B01_synthetic", "B01-synthetic"),
        ("B01_organic", "B01-organic"),
        ("B02_synthetic", "B02-synthetic"),
        ("B02_organic", "B02-organic"),
        ("P00_perlin_noise", "P00 (Perlin)"),
        ("P01_sphincs_plus", "P01 {\\smaller (SPHINCS+)}"),
    ];

    let emit_row = |out: &mut String, name: &str, cases: u32, vec: &[u32]| {
        let total: u32 = vec.iter().sum();
        let mean = if cases > 0 {
            (total as f64 / cases as f64).round() as u32
        } else {
            0
        };
        let median = median_round(vec);
        let max = vec.iter().copied().max().unwrap_or(0);
        out.push_str(&format!(
            "{} & {} & {} & {} & {} & {} \\\\\n",
            name,
            cases,
            fmt_commas(total),
            fmt_commas(mean),
            fmt_commas(median),
            fmt_commas(max),
        ));
    };

    for (dir_name, display) in batteries {
        let locs = tractor_battery_c_locs(&corpus, dir_name);
        if locs.is_empty() {
            continue;
        }
        emit_row(&mut out, display, locs.len() as u32, &locs);
    }

    out
}

/// tab:prompt-sensitivity body: base ACTOR run plus four prompt ablations, then
/// the cross-prompt swap block. The swap figures come from
/// `manual_constants.toml [prompt_sensitivity]` because those runs are a one-off
/// TRACTOR-subset experiment, not re-derived here.
fn generate_prompt_sensitivity_tex(repo_root: &Path, rows: &[BatteryRow]) -> String {
    use std::collections::HashMap;
    let mut tractor_pass: HashMap<&str, u32> = HashMap::new();
    let mut battery_size: HashMap<&str, u32> = HashMap::new();
    for r in rows {
        *tractor_pass.entry(r.agent.as_str()).or_insert(0) += r.cases_passed;
        let e = battery_size.entry(r.battery.as_str()).or_insert(0);
        *e = (*e).max(r.cases_tested);
    }
    let tractor_total: u32 = battery_size.values().sum();

    // (paper label, results-dir agent key); base row first.
    let variants: &[(&str, &str)] = &[
        ("ACTOR (Claude Code)", "claude"),
        ("\\textit{no-subtask}", "claude-no-subtask"),
        ("\\textit{no-iterate}", "claude-no-iter"),
        ("\\textit{no-features}", "claude-no-features"),
        ("\\textit{minimal}", "claude-minimal"),
    ];

    let mut out = String::new();
    out.push_str("% GENERATED by harvest-tools report — do not edit\n");
    for (label, agent) in variants {
        let tp = tractor_pass.get(agent).copied().unwrap_or(0);
        out.push_str(&format!("{} & {}/{} \\\\\n", label, tp, tractor_total));
    }

    let ps = prompt_sensitivity_manual(repo_root);
    let g = |k: &str| ps.get(k).cloned().unwrap_or_default();
    out.push_str("\\hline \\hline\n");
    out.push_str("\\multicolumn{2}{l}{\\emph{Cross-prompt swap on TRACTOR B0X (n = 210)}} \\\\\n");
    out.push_str("\\hline\n");
    out.push_str(&format!(
        "\\textit{{lib prompt on execs}} & {} \\\\\n",
        g("lib_prompt_on_execs")
    ));
    out.push_str(&format!(
        "\\textit{{exec prompt on libs}} & {} \\\\\n",
        g("exec_prompt_on_libs")
    ));
    out
}

fn prompt_sensitivity_manual(repo_root: &Path) -> std::collections::BTreeMap<String, String> {
    let mut out = std::collections::BTreeMap::new();
    let path = repo_root.join("manual_constants.toml");
    let Ok(text) = std::fs::read_to_string(&path) else {
        return out;
    };
    let Ok(doc) = text.parse::<toml_edit::DocumentMut>() else {
        return out;
    };
    if let Some(table) = doc.get("prompt_sensitivity").and_then(|t| t.as_table()) {
        for (k, v) in table.iter() {
            if let Some(s) = v.as_str() {
                out.insert(k.to_string(), s.to_string());
            }
        }
    }
    out
}

/// Macro names are `\<CamelSection><CamelKey>`: section `unsafe_categories` with key
/// `c_abi_preservation` becomes `\UnsafeCategoriesCAbiPreservation`. A missing TOML
/// file emits just the header comment; never fails.
fn generate_manual_tex(repo_root: &Path) -> String {
    let mut out = String::new();
    out.push_str("% MANUALLY ENTERED — not derived from data. Source: manual_constants.toml\n");

    let path = repo_root.join("manual_constants.toml");
    let Ok(text) = std::fs::read_to_string(&path) else {
        return out;
    };
    let Ok(doc) = text.parse::<toml_edit::DocumentMut>() else {
        return out;
    };

    let camel = |s: &str| -> String {
        let mut r = String::new();
        for word in s.split('_') {
            let mut chars = word.chars();
            if let Some(first) = chars.next() {
                r.extend(first.to_uppercase());
                r.push_str(chars.as_str());
            }
        }
        r
    };
    // As it appears in the file: scalars unquoted.
    let render = |v: &toml_edit::Value| -> String {
        match v {
            toml_edit::Value::String(s) => s.value().to_string(),
            toml_edit::Value::Integer(i) => i.value().to_string(),
            toml_edit::Value::Float(f) => f.value().to_string(),
            toml_edit::Value::Boolean(b) => b.value().to_string(),
            other => other.to_string().trim().to_string(),
        }
    };

    for (section, item) in doc.iter() {
        let Some(table) = item.as_table() else {
            continue;
        };
        let sec_camel = camel(section);
        for (key, val) in table.iter() {
            let Some(v) = val.as_value() else { continue };
            let macro_name = format!("{}{}", sec_camel, camel(key));
            out.push_str(&format!(
                "\\newcommand{{\\{}}}{{{}}}\n",
                macro_name,
                render(v)
            ));
        }
    }

    out
}

/// The phase whose `result.json` records what was scored: verify if it ran, else translate.
fn scored_phase_dir(case_dir: &Path) -> PathBuf {
    let verified = crate::battery::phase_dir(case_dir, crate::battery::VERIFIED);
    if verified.join("result.json").is_file() {
        verified
    } else {
        crate::battery::phase_dir(case_dir, crate::battery::TRANSLATED)
    }
}

/// Keyed `"battery/case"`; the value is the runner's own build result.
fn case_builds(repo_root: &Path, agent: &str) -> std::collections::BTreeMap<String, bool> {
    let mut out = std::collections::BTreeMap::new();
    let agent_dir = repo_root.join("results/Test-Corpus").join(agent);
    let Ok(bats) = sorted_read_dir(&agent_dir) else {
        return out;
    };
    for be in bats {
        if !be.path().is_dir() {
            continue;
        }
        let battery = be.file_name().to_string_lossy().to_string();
        let Ok(cases) = sorted_read_dir(&be.path()) else {
            continue;
        };
        for ce in cases {
            if !ce.path().is_dir() {
                continue;
            }
            let case = ce.file_name().to_string_lossy().to_string();
            let rp = scored_phase_dir(&ce.path()).join("result.json");
            let Some(r) = read_json::<CaseResult>(&rp) else {
                continue;
            };
            out.insert(
                format!("{battery}/{case}"),
                r.error.as_deref() != Some("build failed"),
            );
        }
    }
    out
}

/// The paper's Laertes claim is the *direction* of these two counts, so they are named:
/// as a `(u32, u32)` the two are interchangeable at every call site and swapping them
/// reverses the claim without changing a type.
struct LaertesDelta {
    /// Compilations Laertes breaks that C2Rust had working.
    broke: u32,
    /// Ones it fixes that C2Rust could not build.
    fixed: u32,
}

fn laertes_vs_c2rust(repo_root: &Path) -> LaertesDelta {
    let c2 = case_builds(repo_root, "c2rust");
    let la = case_builds(repo_root, "laertes");
    let mut d = LaertesDelta { broke: 0, fixed: 0 };
    for (case, c2_ok) in &c2 {
        if let Some(&la_ok) = la.get(case) {
            if *c2_ok && !la_ok {
                d.broke += 1;
            }
            if !*c2_ok && la_ok {
                d.fixed += 1;
            }
        }
    }
    d
}

struct KiroCost {
    credits: Credits,
    /// The verify phase's share OF `credits`, not an addition to it — the published
    /// validate-percentage is the ratio of the two.
    verify_credits: Credits,
    wall_secs: u64,
}

/// Reads exactly ONE result.json per case, the canonical phase dir. Each case
/// may have BOTH translated/result.json and verified/result.json, and the
/// verified one already carries the full translate+verify credit breakdown, so
/// reading both would double-count the translate phase. Shared-source
/// duplicates carry no credits, so they do not inflate the total.
fn kiro_cost(base: &Path) -> KiroCost {
    let zero = || KiroCost {
        credits: Credits::new(0.0),
        verify_credits: Credits::new(0.0),
        wall_secs: 0,
    };
    let (mut total, mut verify, mut secs) = (0.0f64, 0.0f64, 0u64);
    let Ok(rd) = std::fs::read_dir(base) else {
        return zero();
    };
    let mut stack: Vec<std::path::PathBuf> = rd.filter_map(|e| e.ok().map(|e| e.path())).collect();
    while let Some(p) = stack.pop() {
        if !p.is_dir() {
            continue;
        }
        // A case dir is one with a translated/ phase. Do NOT also descend into
        // its phase dirs — each carries a result.json and would double-count.
        if crate::battery::phase_dir(&p, crate::battery::TRANSLATED).is_dir() {
            let rp = scored_phase_dir(&p).join("result.json");
            if let Some(r) = read_json::<serde_json::Value>(&rp) {
                for ph in ["translate", "verify"] {
                    let c = r
                        .pointer(&format!("/{ph}/credits"))
                        .and_then(|v| v.as_f64())
                        .unwrap_or(0.0);
                    let s = r
                        .pointer(&format!("/{ph}/wall_secs"))
                        .and_then(|v| v.as_u64())
                        .unwrap_or(0);
                    total += c;
                    secs += s;
                    if ph == "verify" {
                        verify += c;
                    }
                }
            }
        } else if let Ok(rd) = std::fs::read_dir(&p) {
            stack.extend(rd.filter_map(|e| e.ok().map(|e| e.path())));
        }
    }
    KiroCost {
        credits: Credits::new(total),
        verify_credits: Credits::new(verify),
        wall_secs: secs,
    }
}

/// Named constants for result numbers quoted in the prose, so text and tables
/// cannot disagree. Only numbers derived directly from the committed results
/// appear here; anything the data does not reproduce is left to the paper text.
fn generate_numbers_tex(rows: &[BatteryRow], repo_root: &Path, kiro_dir: Option<&str>) -> String {
    use std::collections::HashMap;
    let mut total_tests: HashMap<&str, u32> = HashMap::new();
    let mut p01_tests: HashMap<&str, u32> = HashMap::new();
    let mut battery_size: HashMap<&str, u32> = HashMap::new();
    for r in rows {
        let e = battery_size.entry(r.battery.as_str()).or_insert(0);
        *e = (*e).max(r.cases_tested);
    }
    let total_cases: u32 = battery_size.values().sum();
    for r in rows {
        *total_tests.entry(r.agent.as_str()).or_insert(0) += r.cases_passed;
        if r.battery == "P01_sphincs_plus" {
            p01_tests.insert(r.agent.as_str(), r.cases_passed);
        }
    }
    // `--`, NEVER 0. An agent this run did not attest was not measured, and a zero is a positive
    // claim that it passed nothing -- false in print: `\ActorKiroTests` published `0/338` for an agent
    // whose own records say 325/338, and `\ActorCodexTests` `0/338` against 243/338, both because a
    // claude-only run attests claude only and `unwrap_or(0)` answered for the rest.
    let scored = |m: &HashMap<&str, u32>, k: &str, denom: u32| -> String {
        m.get(k)
            .map_or_else(|| "--".to_string(), |n| format!("{n}/{denom}"))
    };
    let mut o = String::new();
    o.push_str("% GENERATED by `harvest-tools report`. Do not edit by hand.\n");
    o.push_str("% Named constants for result numbers quoted in the prose, so text and\n");
    o.push_str("% tables cannot disagree. Values are derived from results/.\n");
    o.push_str(&format!(
        "\\newcommand{{\\TractorTotalCases}}{{{}}}\n",
        total_cases
    ));
    // Same deduped counting as tab:datasets, so prose and table agree.
    let corpus = repo_root.join("test-corpus/Public-Tests");
    let tractor_total_loc: u32 = TRACTOR_BATTERY_DIRS
        .iter()
        .flat_map(|d| tractor_battery_c_locs(&corpus, d))
        .sum();
    if tractor_total_loc > 0 && total_cases > 0 {
        let mean = (tractor_total_loc as f64 / total_cases as f64).round() as u32;
        o.push_str(&format!(
            "\\newcommand{{\\TractorTotalLoc}}{{{}}}\n",
            fmt_commas(tractor_total_loc)
        ));
        o.push_str(&format!("\\newcommand{{\\TractorMeanLoc}}{{{}}}\n", mean));
    }
    // Claude and Codex report no credits, so their costs stay manual in the prose.
    // Deduped per-battery Rust LOC, matching what the tables report.
    let tractor_rust_loc: u32 = rows
        .iter()
        .filter(|r| r.agent == "kiro")
        .map(|r| r.total_loc)
        .sum();
    // (label, results dir, translated-Rust-kLOC denominator)
    // Only kiro's transcripts carry credits, so only kiro has a cost row -- and its directory is the
    // attested one, not a literal that the model pin has since moved.
    let cost_rows: Vec<(&str, &str, u32)> = kiro_dir
        .map(|d| vec![("Tractor", d, tractor_rust_loc)])
        .unwrap_or_default();
    for (name, base, rust_loc) in &cost_rows {
        let cost = kiro_cost(&repo_root.join(base));
        let credits = cost.credits.as_f64();
        if credits <= 0.0 {
            continue;
        }
        let dollars = cost.credits.to_usd().as_f64();
        let minutes = cost.wall_secs as f64 / 60.0;
        let kloc = f64::from(*rust_loc) / 1000.0;
        o.push_str(&format!("\\newcommand{{\\Cost{name}}}{{{:.0}}}\n", dollars));
        o.push_str(&format!(
            "\\newcommand{{\\Cost{name}Minutes}}{{{:.0}}}\n",
            minutes
        ));
        if kloc > 0.0 {
            o.push_str(&format!(
                "\\newcommand{{\\Cost{name}PerKLoc}}{{{:.2}}}\n",
                dollars / kloc
            ));
            o.push_str(&format!(
                "\\newcommand{{\\Cost{name}MinPerKLoc}}{{{:.0}}}\n",
                minutes / kloc
            ));
        }
        o.push_str(&format!(
            "\\newcommand{{\\Cost{name}ValidatePct}}{{{:.0}}}\n",
            cost.verify_credits.as_f64() / credits * 100.0
        ));
    }
    let p01 = kiro_dir.map(|d| kiro_cost(&repo_root.join(d).join("P01_sphincs_plus")));
    if let Some(p01) = p01.filter(|c| c.credits.as_f64() > 0.0) {
        o.push_str(&format!(
            "\\newcommand{{\\CostPOne}}{{{:.2}}}\n",
            p01.credits.to_usd().as_f64()
        ));
        o.push_str(&format!(
            "\\newcommand{{\\CostPOneMinutes}}{{{:.0}}}\n",
            p01.wall_secs as f64 / 60.0
        ));
    }

    o.push_str(&format!(
        "\\newcommand{{\\ActorKiroTests}}{{{}}}\n",
        scored(&total_tests, "kiro", total_cases)
    ));
    o.push_str(&format!(
        "\\newcommand{{\\ActorClaudeTests}}{{{}}}\n",
        scored(&total_tests, "claude", total_cases)
    ));
    o.push_str(&format!(
        "\\newcommand{{\\ActorCodexTests}}{{{}}}\n",
        scored(&total_tests, "codex", total_cases)
    ));
    // The paper says "no validate" where the agent dir says `kiro-translate`.
    // The macro name MUST match paper.tex, else it is an undefined control
    // sequence.
    o.push_str(&format!(
        "\\newcommand{{\\ActorKiroNoValidateTests}}{{{}}}\n",
        scored(&total_tests, "kiro-translate", total_cases)
    ));
    o.push_str(&format!(
        "\\newcommand{{\\ActorKiroPOneTests}}{{{}}}\n",
        scored(&p01_tests, "kiro", 128)
    ));
    o.push_str(&format!(
        "\\newcommand{{\\ActorKiroNoValidatePOneTests}}{{{}}}\n",
        scored(&p01_tests, "kiro-translate", 128)
    ));
    let laertes = laertes_vs_c2rust(repo_root);
    o.push_str(&format!(
        "\\newcommand{{\\LaertesBreaks}}{{{}}}\n",
        laertes.broke
    ));
    o.push_str(&format!(
        "\\newcommand{{\\LaertesFixes}}{{{}}}\n",
        laertes.fixed
    ));
    o
}

/// In paper order: ACTOR harness rows first, then transpiler/LLM baselines.
/// How a run's own label is spelled in the paper. A NAME, and nothing else.
///
/// This is all that survives of `TRACTOR_TABLE_ROWS`, which paired each label with a results
/// directory and an is-ACTOR flag -- three facts in one literal, and two of them already derivable.
/// It keyed codex on `codex-gpt54` while `Run::label` produces `codex`, so codex's row was skipped as
/// "absent" rather than printed; and it doubled as the list of agents that must EXIST, which is why a
/// legitimate model rename made the whole table refuse.
fn display_label(run_label: &str) -> String {
    match run_label {
        "kiro" => "ACTOR (Kiro)".to_string(),
        "claude" => "ACTOR (Claude Code)".to_string(),
        "codex" => "ACTOR (Codex)".to_string(),
        NO_VALIDATE => "\\makebox[\\knvLength][l]{ACTOR (Kiro, no validate)}".to_string(),
        "c2rust" => "C2Rust".to_string(),
        "laertes" => "Laertes".to_string(),
        "c2saferrust" => "C2SaferRust".to_string(),
        "smartc2rust" => "SmartC2Rust".to_string(),
        "kimi" => "Kimi K2.5 (query)".to_string(),
        // An ablation or a tool with no paper spelling prints its own label rather than vanishing.
        other => other.to_string(),
    }
}

/// The synthetic pre-verify row kiro contributes; see where it is pushed in `generate`.
const NO_VALIDATE: &str = "kiro-translate";

/// The agent rows to print, in paper order, DERIVED from the rows this run built.
///
/// Order is declared (ACTOR harnesses first, then baselines, deterministic within each) but
/// MEMBERSHIP is not: a tool appears because it produced rows, not because it is on a list. That is
/// what stops a renamed directory being indistinguishable from a baseline that was never run.
fn agent_rows(rows: &[BatteryRow]) -> Vec<(String, String, bool)> {
    let mut agents: Vec<&str> = rows.iter().map(|r| r.agent.as_str()).collect();
    agents.sort_unstable();
    agents.dedup();
    // `is_agentic` is the one definition of "an ACTOR harness"; clap's ValueEnum gives the domain, so
    // a tool added later is classified without touching this file.
    let is_actor = |a: &str| {
        use clap::ValueEnum;
        a == NO_VALIDATE
            || crate::cli::Tool::value_variants()
                .iter()
                .any(|t| a.starts_with(crate::cli::tool_dir(*t)))
    };
    let mut out: Vec<(String, String, bool)> = agents
        .iter()
        .map(|a| (display_label(a), (*a).to_string(), is_actor(a)))
        .collect();
    out.sort_by_key(|(_, a, actor)| (!*actor, a.clone()));
    out
}

/// In paper order. Each entry is (label on the first agent row, label on the
/// second, dir): P00/P01 split their name across two rows to match the paper's
/// layout, the others put the whole label on line 1.
const TRACTOR_BATTERIES: &[(&str, &str, &str)] = &[
    ("B01-syn", "", "B01_synthetic"),
    ("B01-org", "", "B01_organic"),
    ("B02-syn", "", "B02_synthetic"),
    ("B02-org", "", "B02_organic"),
    ("P00", "(Perlin)", "P00_perlin_noise"),
    (
        "P01",
        "\\makebox[1cm][l]{\\smaller (SPHINCS+)}",
        "P01_sphincs_plus",
    ),
    ("Total", "", ""), // empty battery dir => aggregate across all
];

/// Matches the paper table's LOC formatting.
fn fmt_k(loc: u32) -> String {
    if loc < 1000 {
        loc.to_string()
    } else if loc < 2000 {
        format!("{:.1}k", loc as f64 / 1000.0)
    } else {
        format!("{}k", (loc as f64 / 1000.0).round() as u32)
    }
}

/// tab:tractor body rows only; the table/tabular/caption stays in paper.tex.
fn generate_tractor_tex(rows: &[BatteryRow]) -> String {
    use std::collections::HashMap;
    // (agent dir, battery dir) -> row
    let mut idx: HashMap<(&str, &str), &BatteryRow> = HashMap::new();
    for r in rows {
        idx.insert((r.agent.as_str(), r.battery.as_str()), r);
    }

    // Largest cases_tested any agent recorded = the full battery size, since the
    // ACTOR harnesses ran every case. A baseline's partial run still divides by
    // it, so a case it never attempted counts as a failure (paper methodology).
    let mut battery_size: HashMap<&str, u32> = HashMap::new();
    for r in rows {
        let e = battery_size.entry(r.battery.as_str()).or_insert(0);
        *e = (*e).max(r.cases_tested);
    }
    // Derived, not hardcoded, so it stays correct if the corpus changes.
    let total_cases: u32 = TRACTOR_BATTERIES
        .iter()
        .filter(|&(_, _, d)| !d.is_empty())
        .map(|(_, _, d)| battery_size.get(d).copied().unwrap_or(0))
        .sum();

    struct Cell {
        built: u32,
        denom: u32,
        tests_pass: u32,
        loc: u32,
        unsafe_lines: u32,
        present: bool,
    }
    let cell = |agent: &str, bat_dir: &str| -> Cell {
        if bat_dir.is_empty() {
            let (mut b, mut tp, mut loc, mut un) = (0u32, 0u32, 0u32, 0u32);
            let mut present = false;
            for (_, _, bd) in TRACTOR_BATTERIES.iter().filter(|(_, _, d)| !d.is_empty()) {
                if let Some(r) = idx.get(&(agent, *bd)) {
                    present = true;
                    b += r.cases_built;
                    tp += r.cases_passed;
                    loc += r.total_loc;
                    un += r.unsafe_lines;
                }
            }
            Cell {
                built: b,
                denom: total_cases,
                tests_pass: tp,
                loc,
                unsafe_lines: un,
                present,
            }
        } else {
            let denom = battery_size.get(bat_dir).copied().unwrap_or(0);
            if let Some(r) = idx.get(&(agent, bat_dir)) {
                Cell {
                    built: r.cases_built,
                    denom,
                    tests_pass: r.cases_passed,
                    loc: r.total_loc,
                    unsafe_lines: r.unsafe_lines,
                    present: true,
                }
            } else {
                Cell {
                    built: 0,
                    denom,
                    tests_pass: 0,
                    loc: 0,
                    unsafe_lines: 0,
                    present: false,
                }
            }
        }
    };

    let mut out = String::new();
    out.push_str(
        "% GENERATED by `harvest-tools report` from results/Test-Corpus/. Do not edit by hand.\n",
    );
    out.push_str("% Builds = crate compiles (result.json error != \"build failed\").\n");
    out.push_str("% Tests = cases passing all vectors. Every system is scored over all cases.\n");

    for (bi, (bat_line1, bat_line2, bat_dir)) in TRACTOR_BATTERIES.iter().enumerate() {
        // Bold goes to the best Tests among ACTOR harness rows.
        let printable = agent_rows(rows);
        let best = printable
            .iter()
            .filter(|(_, _, actor)| *actor)
            .map(|(_, a, _)| cell(a, bat_dir).tests_pass)
            .max()
            .unwrap_or(0);
        // The label goes on the first row EMITTED: rows are skipped, so index 0 left blocks bare.
        let mut emitted = 0usize;
        for (label, agent, _) in &printable {
            let c = cell(agent, bat_dir);
            // A system this run did not resolve is ABSENT, never zeroed: `0/85` reads as "scored
            // zero", which is a claim. Invariant (1c) names that hazard for a missing agent dir.
            if !c.present {
                continue;
            }
            let denom = c.denom;
            let first_col = match emitted {
                0 => *bat_line1,
                1 => *bat_line2,
                _ => "",
            };
            let label = label.as_str();
            emitted += 1;
            let tests = if c.tests_pass == best && best > 0 {
                format!("\\textbf{{{}/{}}}", c.tests_pass, denom)
            } else {
                format!("{}/{}", c.tests_pass, denom)
            };
            // "--" only when the system produced no output at all for this
            // battery (the paper's dashes for e.g. SmartC2Rust P01).
            let (loc, un) = if c.present && c.loc > 0 {
                (
                    fmt_k(c.loc),
                    format!(
                        "{}\\%",
                        (c.unsafe_lines as f64 / c.loc as f64 * 100.0).round() as u32
                    ),
                )
            } else {
                ("--".into(), "--".into())
            };
            out.push_str(&format!(
                "{} & {} & {}/{} & {} & {} & {} \\\\\n",
                first_col, label, c.built, denom, tests, loc, un
            ));
        }
        // An out-of-scope battery would otherwise leave a doubled \hline where its rows were.
        if emitted == 0 {
            continue;
        }
        if bi + 2 == TRACTOR_BATTERIES.len() {
            out.push_str("\\hline\\hline\n");
        } else if bi + 1 < TRACTOR_BATTERIES.len() {
            out.push_str("\\hline\n");
        }
    }
    out
}

/// Three same-width counts feeding three different published columns — one of them the
/// unsafe percentage, which is `unsafe_lines / total_loc`. As a `(u32, u32, u32)` any
/// permutation type-checks at every call site and lands in the table relabelled.
struct CaseTotals {
    total_loc: u32,
    unsafe_lines: u32,
    cases_built: u32,
}

/// `corpus_bat_dir` is the matching `test-corpus/Public-Tests/<battery>`, needed to dedup
/// shared-source LOC.
///
/// Two quantities, two rules. `built` counts EVERY config (P01 = 128/128, all compiled and run despite
/// sharing one translation), whereas `loc`/`unsafe` describe the translated code, which for a
/// shared-source group exists ONCE -- every config's result.json repeats the same LOC, so summing
/// multiplies it. Followers are identified by a symlinked corpus `test_case/`, authoritative rather than
/// a LOC-ratio guess; without the corpus that is unresolvable, so LOC/unsafe sum every case (correct for
/// the all-independent batteries, and only P00/P01 need dedup).
fn aggregate_cases(bat_dir: &Path, corpus_bat_dir: &Path) -> CaseTotals {
    aggregate_cases_phase(bat_dir, corpus_bat_dir, None)
}

/// `phase`: `Some("translated")` for the pre-verify (no-validate) numbers, `None` for the phase [`scored_phase_dir`] picks.
fn aggregate_cases_phase(bat_dir: &Path, corpus_bat_dir: &Path, phase: Option<&str>) -> CaseTotals {
    let corpus_present = corpus_bat_dir.is_dir();
    let (mut total_loc, mut total_unsafe, mut built) = (0u32, 0u32, 0u32);
    let Ok(entries) = std::fs::read_dir(bat_dir) else {
        return CaseTotals {
            total_loc: 0,
            unsafe_lines: 0,
            cases_built: 0,
        };
    };
    for entry in entries.flatten() {
        if !entry.path().is_dir() {
            continue;
        }
        let phase_dir = match phase {
            Some(p) => crate::battery::phase_dir(&entry.path(), p),
            None => scored_phase_dir(&entry.path()),
        };
        let result_path = phase_dir.join("result.json");
        let cr: CaseResult = match read_json(&result_path) {
            Some(r) => r,
            None => continue,
        };
        if cr.error.as_deref() != Some("build failed") {
            built += 1;
        }
        // Skip shared-source followers so one translation is counted once.
        if corpus_present {
            let tc = corpus_bat_dir.join(entry.file_name()).join("test_case");
            if tc.is_symlink() {
                continue;
            }
        }
        total_loc += cr.loc.map_or(0, |l| l.code);
        total_unsafe += cr.unsafe_.map_or(0, |u| u.lines);
    }
    CaseTotals {
        total_loc,
        unsafe_lines: total_unsafe,
        cases_built: built,
    }
}

fn read_json<T: serde::de::DeserializeOwned>(path: &Path) -> Option<T> {
    let data = std::fs::read_to_string(path).ok()?;
    serde_json::from_str(&data).ok()
}

fn sorted_read_dir(dir: &Path) -> Result<Vec<std::fs::DirEntry>> {
    let mut entries: Vec<_> = std::fs::read_dir(dir)?.filter_map(|e| e.ok()).collect();
    entries.sort_by_key(|e| e.file_name());
    Ok(entries)
}

/// Non-blank, non-comment `*.c`/`*.h` lines. Shared-source cases symlink their
/// `test_case/` to one real source; each DISTINCT resolved source is counted
/// once, so P01's 128 configs contribute their one source a single time.
fn count_c_loc_battery(test_corpus_dir: &Path, battery: &str) -> u32 {
    let bat_dir = test_corpus_dir.join(battery);
    let Ok(entries) = std::fs::read_dir(&bat_dir) else {
        return 0;
    };
    let mut total = 0u32;
    let mut seen: std::collections::HashSet<std::path::PathBuf> = std::collections::HashSet::new();
    for entry in entries.flatten() {
        if !entry.path().is_dir() {
            continue;
        }
        let test_case = entry.path().join("test_case");
        if !test_case.is_dir() {
            continue;
        }
        let real = std::fs::canonicalize(&test_case).unwrap_or_else(|_| test_case.clone());
        if !seen.insert(real) {
            continue;
        }
        total += count_c_loc_dir(&test_case);
    }
    total
}

fn count_c_loc_dir(dir: &Path) -> u32 {
    let mut total = 0u32;
    let Ok(entries) = std::fs::read_dir(dir) else {
        return 0;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            total += count_c_loc_dir(&path);
        } else if path.extension().is_some_and(|x| x == "c" || x == "h") {
            let Ok(src) = std::fs::read_to_string(&path) else {
                continue;
            };
            total += src
                .lines()
                .filter(|l| {
                    let t = l.trim();
                    !t.is_empty() && !t.starts_with("//") && !t.starts_with("/*")
                })
                .count() as u32;
        }
    }
    total
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_tool_that_produced_rows_gets_a_number_not_a_dash() {
        let tmp = crate::io::workdir::test_tempdir().unwrap();
        let row = |agent: &str| BatteryRow {
            agent: agent.to_string(),
            battery: "B01_organic".to_string(),
            cases_passed: 7,
            cases_tested: 7,
            cases_built: 7,
            vectors_passed: 1,
            vectors_total: 1,
            c_loc: 1,
            total_loc: 1,
            unsafe_lines: 0,
        };
        let out = generate_numbers_tex(
            &[row("claude"), row("codex"), row("kiro")],
            tmp.path(),
            None,
        );
        for name in ["ActorClaudeTests", "ActorCodexTests", "ActorKiroTests"] {
            let line = out
                .lines()
                .find(|l| l.contains(name))
                .unwrap_or_else(|| panic!("{name} is not emitted at all"));
            assert!(
                line.contains("7/7") && !line.contains("--"),
                "{name} must carry the number its rows prove: {line}"
            );
        }
        let alone = generate_numbers_tex(&[row("claude")], tmp.path(), None);
        let codex = alone
            .lines()
            .find(|l| l.contains("ActorCodexTests"))
            .expect("the macro is always emitted");
        assert!(codex.contains("--"), "absent must be a dash: {codex}");
    }

    /// An agent this run did not attest renders `--`, never `0/338`.
    ///
    /// A claude-only run attests claude only, and `unwrap_or(0)` answered for everyone else -- so
    /// `numbers.tex` shipped `\ActorKiroTests{0/338}` for an agent whose own committed records say
    /// 325/338, and `\ActorCodexTests{0/338}` against 243/338. A zero is a claim; absence is not.
    /// Membership is DERIVED, so a tool appears because it produced rows. The frozen list keyed codex
    /// on `codex-gpt54` while `Run::label` produces `codex`, so codex's row was skipped as "absent"
    /// even with a full battery of results behind it -- and the same list doubled as the set of
    /// directories that must exist, which made the `<tool>/<model>` rename refuse every table.
    #[test]
    fn a_tool_gets_a_row_because_it_produced_one_not_because_it_is_on_a_list() {
        let row = |agent: &str| BatteryRow {
            agent: agent.to_string(),
            battery: "B01_organic".to_string(),
            cases_passed: 1,
            cases_tested: 1,
            cases_built: 1,
            vectors_passed: 1,
            vectors_total: 1,
            c_loc: 1,
            total_loc: 1,
            unsafe_lines: 0,
        };
        let got = agent_rows(&[row("codex"), row("claude"), row("kiro"), row("c2rust")]);
        let keys: Vec<&str> = got.iter().map(|(_, a, _)| a.as_str()).collect();
        assert!(
            keys.contains(&"codex"),
            "codex produced rows and must be printable: {keys:?}"
        );
        // ACTOR harnesses first, baselines after -- order declared, membership not.
        let actor: Vec<bool> = got.iter().map(|(_, _, a)| *a).collect();
        assert_eq!(actor, vec![true, true, true, false], "{keys:?}");
        assert_eq!(
            got[3].0, "C2Rust",
            "a baseline still gets its paper spelling"
        );
        // A tool with NO rows must not appear at all: an absent system is a dash, never a zero.
        assert!(
            !agent_rows(&[row("claude")])
                .iter()
                .any(|(_, a, _)| a == "kiro"),
            "kiro produced nothing and must not be listed"
        );
    }

    #[test]
    fn an_unattested_agent_renders_a_dash_not_a_zero() {
        let mut m: BTreeMap<&str, u32> = BTreeMap::new();
        m.insert("claude", 335);
        let scored = |m: &BTreeMap<&str, u32>, k: &str, denom: u32| -> String {
            m.get(k)
                .map_or_else(|| "--".to_string(), |n| format!("{n}/{denom}"))
        };
        assert_eq!(scored(&m, "claude", 338), "335/338");
        assert_eq!(
            scored(&m, "kiro", 338),
            "--",
            "an agent with no entry was NOT measured; 0/338 asserts it passed nothing"
        );
        // Non-vacuity: a genuine zero still prints as a zero.
        m.insert("smartc2rust", 0);
        assert_eq!(scored(&m, "smartc2rust", 338), "0/338");
    }

    /// `wrote_any` was the only guard, so six missing records still produced a one-row table and a ✅ --
    /// the `N/6 projects pass` defect one layer up.
    #[test]
    fn a_table_missing_an_attested_projects_record_is_refused_not_published_short() {
        let tmp = crate::io::workdir::test_tempdir().unwrap();
        // The key's own `dir()`: a fixture spelling the path itself would survive a layout change.
        let paths = crate::battery::Paths::new(
            tmp.path(),
            crate::cli::Tool::Claude,
            crate::cli::Variant::Default,
            crate::cli::Dataset::HarvestBench,
            None,
            crate::store::Mode::ReadWrite,
            crate::io::sandbox::Enforcement::Required,
        )
        .unwrap();
        let hb = paths.results_dir.clone();
        let record = |project: &str| {
            let dir = crate::battery::phase_dir(&hb.join(project), crate::battery::TRANSLATED);
            std::fs::create_dir_all(&dir).unwrap();
            std::fs::write(
                dir.join("result.json"),
                r#"{"tests_ok":5,"tests_failed":0,"tests_skipped":0,"build_ok":true}"#,
            )
            .unwrap();
        };
        record("jansson");

        let mut attested = Attested::default();
        attested.insert(&paths, "jansson");
        attested.insert(&paths, "lz4");

        let table = tmp.path().join("tables/harvest-bench.tex");
        let err = generate_harvest_bench(tmp.path(), &attested)
            .expect_err("lz4 is in scope with no record, so the table cannot claim completeness");
        assert!(
            format!("{err:#}").contains("lz4"),
            "and the refusal must name the project it could not report: {err:#}"
        );
        assert!(
            !table.exists(),
            "nor leave a short table standing for the next reader"
        );

        // Non-vacuity: the refusal must not be firing for some reason that also blocks the good case.
        record("lz4");
        generate_harvest_bench(tmp.path(), &attested).expect("both records exist now");
        let tex = std::fs::read_to_string(&table).unwrap();
        assert!(
            tex.contains("jansson") && tex.contains("lz4"),
            "both attested projects must appear: {tex}"
        );
    }

    /// Every row says WHICH RUN produced it. `run.label` was read for the error message and left out
    /// of the row -- harmless while claude was the only arm with harvest-bench results, and with three
    /// tools it emits three rows called `libsodium` that nothing distinguishes.
    #[test]
    fn every_harvest_bench_row_names_the_run_that_produced_it() {
        let tmp = crate::io::workdir::test_tempdir().unwrap();
        let paths_for = |tool| {
            crate::battery::Paths::new(
                tmp.path(),
                tool,
                crate::cli::Variant::Default,
                crate::cli::Dataset::HarvestBench,
                None,
                crate::store::Mode::ReadWrite,
                crate::io::sandbox::Enforcement::Required,
            )
            .unwrap()
        };
        let mut attested = Attested::default();
        for (tool, ok) in [
            (crate::cli::Tool::Claude, 104),
            (crate::cli::Tool::Codex, 0),
            (crate::cli::Tool::Kiro, 58),
        ] {
            let paths = paths_for(tool);
            let dir = crate::battery::phase_dir(
                &paths.results_dir.join("libsodium"),
                crate::battery::TRANSLATED,
            );
            std::fs::create_dir_all(&dir).unwrap();
            std::fs::write(
                dir.join("result.json"),
                format!(
                    r#"{{"tests_ok":{ok},"tests_failed":0,"tests_skipped":0,"build_ok":true}}"#
                ),
            )
            .unwrap();
            attested.insert(&paths, "libsodium");
        }

        generate_harvest_bench(tmp.path(), &attested).unwrap();
        let tex = std::fs::read_to_string(tmp.path().join("tables/harvest-bench.tex")).unwrap();
        let rows: Vec<&str> = tex.lines().filter(|l| l.contains("libsodium")).collect();
        assert_eq!(rows.len(), 3, "one row per run: {tex}");
        let labels: std::collections::BTreeSet<String> = rows
            .iter()
            .map(|r| {
                r.split('&')
                    .next()
                    .unwrap_or_default()
                    .trim()
                    .to_lowercase()
            })
            .collect();
        assert_eq!(labels.len(), 3, "three libsodium rows, three labels: {tex}");
        for tool in ["claude", "codex", "kiro"] {
            assert!(
                labels.iter().any(|l| l.contains(tool)),
                "no row names {tool}: {tex}"
            );
        }
        assert!(rows.iter().any(|r| r.contains("104/104")), "{tex}");
        assert!(rows.iter().any(|r| r.contains("58/58")), "{tex}");
    }
}
